name: The Next LexingtonKy.gov
baseurl: /next
exclude: [Gemfile, Gemfile.lock, Dockerfile, fig.yml, docker-compose.yml]
markdown: redcarpet
redcarpet:
  extensions: ["with_toc_data", "tables", "fenced_code_blocks"]
