name: Erik Schwartz
description: "Erik Schwartz's blog, projects, and vine"
url: http://lfucg.github.io/next
permalink: /slug/
exclude: [Gemfile, Gemfile.lock, Dockerfile, fig.yml, docker-compose.yml]
markdown: redcarpet
